name: generate panvimdocs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: grapple.nvim
          version: "NVIM v0.8.0"
          demojify: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(docs): auto generate docs'
          branch: ${{ github.head_ref }}
